### ISSUE TITLE
Usage of function

### ISSUE THREAD

**Issue by cmehra890** [AllAlgorithms/c#158]
What is the the syntax of using function

**Comment by tyadav4268** [comment]
syntax for using a function:-
let take an example of add function:
1. int add(int a, int b)
2. {
3.    return a+b;
4. }
first line tells that the function have to return an integer and takes two integer arguments.
this function should be created  before int main() or a declaration of this function to be created before int main() function and then this function can be written after the ending of main() function. Declaration of function is also called function prototype. So for the above function the prototype would be:-
int add(int, int);
