### ISSUE TITLE
Do you know any algorithm in C?

### ISSUE THREAD

**Issue by abrahamcalf** [AllAlgorithms/c#168]
<p align="center">
  <img src="https://cdn.abranhe.com/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [C](https://github.com/AllAlgorithms/c) this case

**Comment by shivanigupta19** [comment]
yes i wanted to work on this

**Comment by Rj-coder-iitian** [comment]
@abranhe  I can implement bubble, insertion, selection, merge sort in c language.
If that can me needed then please assign me.

**Comment by Aliex-dev** [comment]
i can implement the algo to convert a matrix to sparse matrix

**Comment by watashi-wa-sidhant** [comment]
sparse matrix addition and multiplication?

**Comment by SunnyRaj2424** [comment]
please assign me for this task. 🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻

**Comment by SunnyRaj2424** [comment]
Yes

**Comment by VIPUL662** [comment]
yes sir i want to contribute to your project 
i will impliment decimal to hexadecimal conversion 
please give me chance sir

**Comment by VIPUL662** [comment]
i will find determinent of square matrix on n*n in very efficient way please give me chance sir

**Comment by SunnyRaj2424** [comment]
Sir , I can do the algorithm to search , insert or delete any data from any
list in a data structure using C programming language, or if you want me to
do something else you can mail me.

**Comment by watashi-wa-sidhant** [comment]
comment

**Comment by abhishektanwar2001** [comment]
@abranhe i can do a lot good things in c if possible give me pleasure to have a look upon this project for its fruitment

**Comment by maw1a** [comment]
@abranhe I read about this sorting algorithm somewhere using time. I would like to contribute my implementation of the same algorithm in C.

**Comment by scnew** [comment]
I have some algorithms that deal with simple moving averages.  Does anyone think that simple moving averages are something that belongs here in C?

**Comment by GGmaria** [comment]
I know Algorithms to perform tree operations

**Comment by hypnotizedhero-git** [comment]
@abranhe sir, I wanted to work on this. I know how to code in C/C++ efficiently and diligently.

**Comment by pranavaeron** [comment]
sir i can work on making algorithm for making a list of the data collected from the users and store it in a file where we can review the input data.
i will do this with the help of structure and print that data from structure to the file because if we wanna read the data anytime in future we can read and store it in structure.
so sir please give me the chance to work on this

**Comment by eddybruv** [comment]
I can so the Odd Even sorting algorithm

**Comment by Bhagyanekraje** [comment]
Sir,I would like to contribute for your work.I know few specific algorithms in C that can be shared with you if you allow.

**Comment by neetu-749** [comment]
Sir I want to work on this for greedy technique based algorithms.

**Comment by 1432junaid** [comment]
hello there, I can implement **Bankers Algorithm** in C.

**Comment by AnirudhDaya** [comment]
Hello, I can implement a few disk scheduling algorithms in C. It would be a great addition to your repo.

**Comment by SR-Sunny-Raj** [comment]
According to hacktoberfest 2022 rules you can only make one valid PR in any specific repository, so request you to please not make a lot of contribution in a single repository otherwise it will get marked as spam. Hope you can understand it and will keep in mind from ahead.

**Comment by SR-Sunny-Raj** [comment]
Please make your contribution in this repository https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-all for 2022 hacktoberfest.

**Comment by Raja-Muhammad-Bilal-Arshad** [comment]
I can provide some algorithms in C/C++ languages regarding Heap Sort, Quick Sort, Merge Sort etc...
