### ISSUE TITLE
Do you any algorithm on C?

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/c#2]
<p align="center">
  <img src="https://cdn.abranhe.com/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [C](https://github.com/AllAlgorithms/c) this case

**Comment by DinahLin** [comment]
Can I work on it?

**Comment by abranhe** [comment]
@DinahLin yes for sure you can contribute to this project!

**Comment by Shivansh9340** [comment]
hi

**Comment by guns77** [comment]
Can I contribute??

**Comment by abhi1998das** [comment]
can i contribute?

**Comment by yukta12** [comment]
Algorithms related to Operating systems can be added here?
Can i do that?

**Comment by sakshamdoda** [comment]
Can I contribute?
