### ISSUE TITLE
C language

### ISSUE THREAD

**Issue by Aakash2392** [AllAlgorithms/c#338]

**Comment by srigani** [comment]
![IMG20210701172544_00.jpg](https://user-images.githubusercontent.com/86564998/124120430-697f5e00-da91-11eb-8c60-66ab6e7689cf.jpg) I am getting a run time debug assertion in this program

**Comment by rohit96310** [comment]
hey, change "scanf_s" to "scanf' and in while condition write "num!=0" instead of "0.0" because your num is of int data type so it value cannot be 0.0.. hope this might help

**Comment by SnakeX-cell** [comment]
Write scanf properly and in while write 0 only bcz its data type is not float

**Comment by SnakeX-cell** [comment]
> hey, change "scanf_s" to "scanf("%d", &sum); " and in while condition write "num!=0" instead of "0.0" because your num is of int data type so it value cannot be 0.0.. hope this might help 
> note : there must not be any space  between % and d it must be written as %d..
> 

scanf("%d",&sum); can you explain me how.in my opinion it should be scanf("%d",&num);
